[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "alsa-lib",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "mesa",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libxcb"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
